<a href="https://colab.research.google.com/github/Suhuyini15/PYTORCH_P/blob/main/00_pytorch_EXERCISE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q2 - RANDOM TENSOR

In [ ]:
import torch

In [ ]:
x = torch.rand(7,7)
x

tensor([[0.0857, 0.1447, 0.8453, 0.5417, 0.1271, 0.3060, 0.3423],
        [0.6491, 0.4356, 0.8049, 0.4086, 0.5487, 0.0961, 0.1700],
        [0.3561, 0.4308, 0.1417, 0.0736, 0.1153, 0.5190, 0.7784],
        [0.0923, 0.6005, 0.7445, 0.7685, 0.5465, 0.4888, 0.2469],
        [0.0513, 0.7274, 0.7389, 0.3108, 0.1186, 0.7774, 0.6678],
        [0.6768, 0.3139, 0.9360, 0.7000, 0.2321, 0.5592, 0.1524],
        [0.9366, 0.5470, 0.9511, 0.6157, 0.1955, 0.9954, 0.8655]])

Q3 - MATRIX MULTIPLICATION

In [ ]:
y = torch.rand(1,7)
y

tensor([[0.7268, 0.1611, 0.0609, 0.3698, 0.7130, 0.8365, 0.2945]])

In [ ]:
torch.matmul(y,x)

tensor([[1.1011, 1.3659, 2.6179, 1.7366, 0.7262, 1.7654, 1.2734]])

In [ ]:
torch.matmul(x,y.T)

tensor([[0.7848],
        [1.2637],
        [1.1097],
        [1.3645],
        [1.2459],
        [1.5364],
        [2.2813]])

Q4 - RANDOM SEED

In [ ]:
# r_seed = 0
torch.manual_seed(0)
x = torch.rand(7,7)
y = torch.rand(1,7)
print(f'first tensor:\n{x}\n\n second tensor:\n{y}')


first tensor:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

 second tensor:
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


Q5 - RANDOM SEED (GPU)

In [ ]:
torch.manual_seed(1234)
x = torch.rand(7,7).cuda()
y = torch.rand(1,7).cuda()
print(f'first tensor:\n{x}\n\n second tensor:\n{y}')
#

first tensor:
tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]],
       device='cuda:0')

 second tensor:
tensor([[0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149, 0.3993]],
       device='cuda:0')


Q6 - RANDOM TENSOR (GPU)

In [ ]:
torch.manual_seed(1234)
x = torch.rand(2,3).cuda()
y = torch.rand(2,3).cuda()
print(f'first tensor:\n{x}\n\n second tensor:\n{y}')

first tensor:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

 second tensor:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


Q7 - MATMUL

In [ ]:
result = torch.matmul(x,y.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

Q8 - MIN AND MAX VALUE

In [ ]:
result.max(), result.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

Q9 - MIN AND MAX INDEX

In [ ]:
result.argmax(), result.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

Q10 - SQUEEZE

In [ ]:
torch.manual_seed(7)
random1 = torch.rand(1,1,1,10)
random1, random1.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [ ]:
torch.manual_seed(7)
change = random1.squeeze()
change, change.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))