<a href="https://colab.research.google.com/github/Suhuyini15/PYTORCH_P/blob/main/00_PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


CREATING TENSORS


In [2]:
#SCALAR

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#gET TENSOR AS PYTHON int
scalar.item()

7

In [5]:
#VECTOR
vector = torch.tensor([2,6])
vector

tensor([2, 6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [2,6]])

MATRIX

tensor([[7, 8],
        [2, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([2, 6])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],[5,9,1],
                       [6,4,7]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 9, 1],
        [6, 4, 7]])

In [16]:
MATRIX2 = torch.tensor([[[7,0,4],
            [5,9,1],
            [6,3,5]]])

In [17]:
MATRIX2.ndim

3

RANDOM TENSORS

Neural network pattern

```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
```



In [18]:
#Random Tensors
random_tensor = torch.rand(5, 4,6)
random_tensor

tensor([[[0.9811, 0.0645, 0.5532, 0.1740, 0.6766, 0.4255],
         [0.8584, 0.8601, 0.0686, 0.4524, 0.2530, 0.0186],
         [0.9350, 0.8512, 0.4387, 0.0174, 0.2154, 0.3290],
         [0.1235, 0.7378, 0.2975, 0.4434, 0.5004, 0.9271]],

        [[0.9547, 0.9128, 0.0030, 0.7879, 0.4271, 0.1420],
         [0.9942, 0.7418, 0.9109, 0.7143, 0.6479, 0.7329],
         [0.4275, 0.9154, 0.1475, 0.1229, 0.2861, 0.2489],
         [0.5443, 0.9510, 0.3230, 0.5464, 0.5611, 0.7585]],

        [[0.4273, 0.1924, 0.7662, 0.8229, 0.0847, 0.8580],
         [0.3942, 0.7734, 0.1778, 0.1386, 0.2671, 0.0540],
         [0.8843, 0.7403, 0.0915, 0.1201, 0.0114, 0.7552],
         [0.0902, 0.7705, 0.3269, 0.7569, 0.4513, 0.1204]],

        [[0.3353, 0.1204, 0.7149, 0.2256, 0.5040, 0.5768],
         [0.1973, 0.8047, 0.9259, 0.2637, 0.4550, 0.8037],
         [0.0917, 0.8226, 0.1197, 0.2114, 0.7044, 0.5221],
         [0.0442, 0.5492, 0.1717, 0.1086, 0.8516, 0.2382]],

        [[0.6837, 0.5969, 0.1478, 0.8165, 0.1470

In [19]:
random_tensor.ndim

3

In [20]:
#Tensor with shape similar to an image
random_image_tensor = torch.rand(size =(224,224,3))# height, widht ,color channel
random_image_tensor.shape,random_image_tensor.ndim





(torch.Size([224, 224, 3]), 3)

In [21]:
CAT_TENSOR = torch.rand(2,7,2,2)
CAT_TENSOR

tensor([[[[0.7536, 0.3232],
          [0.7587, 0.1482]],

         [[0.4872, 0.2476],
          [0.1711, 0.2862]],

         [[0.7111, 0.5250],
          [0.9705, 0.8118]],

         [[0.8761, 0.1973],
          [0.1536, 0.8655]],

         [[0.2480, 0.9608],
          [0.0405, 0.0414]],

         [[0.8451, 0.7969],
          [0.3506, 0.2986]],

         [[0.5667, 0.1389],
          [0.7931, 0.2623]]],


        [[[0.5726, 0.6537],
          [0.2053, 0.6522]],

         [[0.4027, 0.5529],
          [0.6269, 0.8200]],

         [[0.8840, 0.1091],
          [0.5568, 0.9892]],

         [[0.4805, 0.8709],
          [0.2896, 0.3200]],

         [[0.7595, 0.7415],
          [0.9584, 0.8659]],

         [[0.4460, 0.4690],
          [0.9541, 0.2686]],

         [[0.4609, 0.8400],
          [0.3140, 0.5260]]]])

In [22]:
CAT_TENSOR.ndim, CAT_TENSOR.shape

(4, torch.Size([2, 7, 2, 2]))

In [23]:
PAINT_IMAGE = torch.rand(size=(155,155,1))

In [24]:
PAINT_IMAGE.ndim, PAINT_IMAGE.shape

(3, torch.Size([155, 155, 1]))

**ZEROS AND ONES**

In [25]:
Zeros = torch.zeros(5,4,6)
Zeros

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [26]:
Zeros*random_tensor

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [27]:
Ones = torch.ones(size=(5,9))
Ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
numbers = torch.arange(1000,1000000,10000)
numbers

tensor([  1000,  11000,  21000,  31000,  41000,  51000,  61000,  71000,  81000,
         91000, 101000, 111000, 121000, 131000, 141000, 151000, 161000, 171000,
        181000, 191000, 201000, 211000, 221000, 231000, 241000, 251000, 261000,
        271000, 281000, 291000, 301000, 311000, 321000, 331000, 341000, 351000,
        361000, 371000, 381000, 391000, 401000, 411000, 421000, 431000, 441000,
        451000, 461000, 471000, 481000, 491000, 501000, 511000, 521000, 531000,
        541000, 551000, 561000, 571000, 581000, 591000, 601000, 611000, 621000,
        631000, 641000, 651000, 661000, 671000, 681000, 691000, 701000, 711000,
        721000, 731000, 741000, 751000, 761000, 771000, 781000, 791000, 801000,
        811000, 821000, 831000, 841000, 851000, 861000, 871000, 881000, 891000,
        901000, 911000, 921000, 931000, 941000, 951000, 961000, 971000, 981000,
        991000])

In [29]:
#Creating tensosr like (A tensor with the shpae like another or previous tensor)
numbers_zeros = torch.zeros_like(input=numbers)
numbers_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [30]:
numbers_ones = torch.ones_like(input=numbers)
numbers_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

**TENSOR DATATYPES**

In [31]:
FLOAT_32_TENSOR = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,# tensor datatype
                               device='cpu', # devive of tensor
                               requires_grad=False) # track gradient or not
FLOAT_32_TENSOR

tensor([3., 6., 9.])

In [32]:
FLOAT_32_TENSOR.dtype

torch.float32

In [33]:
#CHANGE TENSOR DYTPE
FLOAT_16_TENSOR = FLOAT_32_TENSOR.type(torch.float16)
FLOAT_16_TENSOR

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
from typing import Tuple
new_tensor = torch.tensor([[1,7],[6,8]],
                          dtype=None,
                          device='cpu',
                          requires_grad=False)
new_tensor.dtype

torch.int64

In [35]:
sample_tensor = torch.empty((5,8), dtype=torch.int8, requires_grad=False)
sample_tensor

tensor([[ -65, -112,   52,   34,    0,    0,    0,    0],
        [   0,    0,    0,    0,    1,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [  97,    0,    0,    0,    0,    0,    0,    0],
        [ -32,  -69,   37,   34,    0,    0,    0,    0]], dtype=torch.int8)

In [36]:
sample_tensor = sample_tensor.type(torch.cdouble)
sample_tensor

tensor([[ -65.+0.j, -112.+0.j,   52.+0.j,   34.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [   0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    1.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [   0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [  97.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [ -32.+0.j,  -69.+0.j,   37.+0.j,   34.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j]],
       dtype=torch.complex128)

*`torch.empty` for creating placeholder tensors.
`torch.tensor` for creating actual tensor with real data *

In [37]:
FLOAT_16_TENSOR*FLOAT_32_TENSOR

tensor([ 9., 36., 81.])

In [38]:
sample2 = torch.ones_like(input=sample_tensor)
sample2

tensor([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]],
       dtype=torch.complex128)

In [39]:
sample2 = sample2.type(torch.int)
sample2

/tmp/ipython-input-4053803223.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at /pytorch/aten/src/ATen/native/Copy.cpp:307.)
  sample2 = sample2.type(torch.int)


tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [40]:
sample_tensor*sample2

tensor([[ -65.+0.j, -112.+0.j,   52.+0.j,   34.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [   0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    1.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [   0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [  97.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
        [ -32.+0.j,  -69.+0.j,   37.+0.j,   34.+0.j,    0.+0.j,    0.+0.j,    0.+0.j,    0.+0.j]],
       dtype=torch.complex128)

 **TOP ERRORS **
1. TENSOR NOT RIGHT DATATYPE
2. TENSOR NOT RIGHT SHAPE
3. TENSOR NOT ON THE RIGHT DEVICE

In [41]:
#GETTING INFO FROM TENSORS
a_tensor = torch.rand(5,3)
a_tensor

tensor([[0.3093, 0.9419, 0.0808],
        [0.0418, 0.4213, 0.8888],
        [0.1732, 0.6234, 0.7599],
        [0.5966, 0.4153, 0.6687],
        [0.9593, 0.5283, 0.6383]])

In [42]:
print(f"Datatype of tensor: {a_tensor.dtype}")
print(f"Shape of tensor: {a_tensor.shape}")
print(f"Device of tensor: {a_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([5, 3])
Device of tensor: cpu


In [43]:
# CHANGING DEVICE OF TENSOR
a_tensor = a_tensor.to(device='cpu')
print(f"Device of tensor: {a_tensor.device}")

Device of tensor: cpu


In [45]:
## ADDITION OF TENSORS
mani_t = torch.tensor([[1,6],[2,8]])
mani_t = mani_t + 3

In [46]:
#MULTIPLY TENSORS
mani_t * 3

tensor([[12, 27],
        [15, 33]])

In [47]:
mani_t

tensor([[ 4,  9],
        [ 5, 11]])

In [48]:
#SUBTRACT
mani_t - 15

tensor([[-11,  -6],
        [-10,  -4]])

In [49]:
#MATRIX FUNCTIONS
torch.mul(mani_t, 1)

tensor([[ 4,  9],
        [ 5, 11]])

In [50]:
## MATRIX MULTIPLICATION
#ELEMENT WISE
print(mani_t ,"*" , mani_t)
print(f"Equals: {mani_t * mani_t}")

tensor([[ 4,  9],
        [ 5, 11]]) * tensor([[ 4,  9],
        [ 5, 11]])
Equals: tensor([[ 16,  81],
        [ 25, 121]])


In [51]:
#MATRIX WISE
%%time
torch.matmul(mani_t, mani_t)

CPU times: user 1.09 ms, sys: 13 µs, total: 1.1 ms
Wall time: 2.68 ms


tensor([[ 61, 135],
        [ 75, 166]])

In [52]:
%%time
#MATRIX WISE
torch.matmul(mani_t, mani_t)

CPU times: user 265 µs, sys: 0 ns, total: 265 µs
Wall time: 520 µs


tensor([[ 61, 135],
        [ 75, 166]])

In [53]:
#OR torch.mm()

#OR

mani_t @ mani_t

tensor([[ 61, 135],
        [ 75, 166]])

In [54]:
torch.matmul(torch.rand(4,3), torch.rand(3,5))

tensor([[0.5904, 0.6106, 0.7230, 1.0140, 0.7750],
        [0.9624, 1.2848, 0.9540, 1.0303, 0.9580],
        [0.2903, 0.3022, 0.1862, 0.2783, 0.2834],
        [0.8596, 0.8960, 0.5016, 0.7586, 0.8103]])

In [55]:
#TENSOR SHAPE ERRORS
one_t = torch.rand(2,3)
two_t = torch.rand(2,3)
one_t , two_t

(tensor([[0.5013, 0.1835, 0.2279],
         [0.7925, 0.5980, 0.6643]]),
 tensor([[0.7263, 0.2175, 0.9765],
         [0.2826, 0.7087, 0.3884]]))

In [56]:
torch.matmul(one_t, two_t)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [57]:
#TRANSPOSE
two_t.T @ one_t

tensor([[0.5881, 0.3023, 0.3533],
        [0.6707, 0.4638, 0.5204],
        [0.7973, 0.4115, 0.4806]])

In [58]:
print(f'Original matrices: \n Tensor 1: {one_t} \n Tensor 2: {two_t}')
print(f'Transpose Tensor 2: {two_t.T}')

Original matrices: 
 Tensor 1: tensor([[0.5013, 0.1835, 0.2279],
        [0.7925, 0.5980, 0.6643]]) 
 Tensor 2: tensor([[0.7263, 0.2175, 0.9765],
        [0.2826, 0.7087, 0.3884]])
Transpose Tensor 2: tensor([[0.7263, 0.2826],
        [0.2175, 0.7087],
        [0.9765, 0.3884]])


**TENSOR AGGREGATION**

In [59]:
X = torch.arange(15,100,8)
X

tensor([15, 23, 31, 39, 47, 55, 63, 71, 79, 87, 95])

In [60]:
#find min
torch.min(X),  X.min()

(tensor(15), tensor(15))

In [61]:
#find max
torch.max(X), X.max()

(tensor(95), tensor(95))

In [62]:
#find mean
torch.mean(X.type(torch.float32)), X.type(torch.float32).mean()

(tensor(55.), tensor(55.))

In [63]:
#find sum
X.sum(), torch.sum(X)

(tensor(605), tensor(605))

In [64]:
#find argmin
X.argmin(), torch.argmin(X)

(tensor(0), tensor(0))

In [65]:
#find argmax
X.argmax(), torch.argmax(X)

(tensor(10), tensor(10))

**RESHAPING, STACKING, SQUEEZING AND UNSQUEEZING TENSORS**

In [66]:
X, X.shape

(tensor([15, 23, 31, 39, 47, 55, 63, 71, 79, 87, 95]), torch.Size([11]))

In [67]:
#Reshape has to be compatible with the original size
X_reshape = X.reshape(1, 11, 1)
X_reshape

tensor([[[15],
         [23],
         [31],
         [39],
         [47],
         [55],
         [63],
         [71],
         [79],
         [87],
         [95]]])

In [68]:
#View
#Changins Z changes X because a view of a tensor shares the same memory as the original tensor
Z = X.view(11,1)
print(f"The view of X is Z: \n{Z}")

Z[3] = -3
print(f"\n\nX after making changes to Z is: {X}")



The view of X is Z: 
tensor([[15],
        [23],
        [31],
        [39],
        [47],
        [55],
        [63],
        [71],
        [79],
        [87],
        [95]])


X after making changes to Z is: tensor([15, 23, 31, -3, 47, 55, 63, 71, 79, 87, 95])


In [69]:
#Stack
X_stack = torch.stack([X,X], dim=1)
X_stack

tensor([[15, 15],
        [23, 23],
        [31, 31],
        [-3, -3],
        [47, 47],
        [55, 55],
        [63, 63],
        [71, 71],
        [79, 79],
        [87, 87],
        [95, 95]])

In [70]:
#Squeeze
A = torch.squeeze(X_reshape)
A

tensor([15, 23, 31, -3, 47, 55, 63, 71, 79, 87, 95])

In [71]:
#Unsqueeze doesn't necessarily undo the squeeze, it adds a dimension whether vertical or horizontal
torch.unsqueeze(A, dim=1)

tensor([[15],
        [23],
        [31],
        [-3],
        [47],
        [55],
        [63],
        [71],
        [79],
        [87],
        [95]])

In [72]:
#PERMUTE
# for scarmbling or rearranging dimentions
original = torch.rand(size=(1,224,224,3))
original_permute = original.permute(0,3,1,2)# 2, 0, 1 represent the various dimensions
original_permute.shape

torch.Size([1, 3, 224, 224])

**INDEXING**

In [73]:
Y = torch.arange(-3, 66, 4).reshape(1,3,6)
Y

tensor([[[-3,  1,  5,  9, 13, 17],
         [21, 25, 29, 33, 37, 41],
         [45, 49, 53, 57, 61, 65]]])

In [74]:
Y[0,0,4]

tensor(13)

In [75]:
Y[:,1,:]

tensor([[21, 25, 29, 33, 37, 41]])

**PYTORCH TENSORS & NUMPY**

In [76]:
#FROM NUMPY TO TENSOR
import numpy as np

arr = np.arange(17,55,2)
arr

array([17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49,
       51, 53])

In [77]:
#Note: 1. Tensor takes default dtype of np array i.e. float64 unless changed manually.
#2. Changes made to array after conversion do not affect tensor
tensor1 = torch.from_numpy(arr)
tensor1

tensor([17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51,
        53])

In [78]:
#Tensor to numpy
tensor2 = torch.ones(2,5)
tensor2

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [79]:
#Note: 1. np array takes default dtype of tensor i.e. float32 unless changed manually.
numpy_tensor = tensor2.numpy()
numpy_tensor

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

REPRODUCIBILITY (NOT SO RANDOM RANDOMNESS)

In [80]:
#RANDOM TNSORS
random_1 = torch.rand(3,3)
rand0m_2 = torch.rand(3,3)
print(random_1)
print(rand0m_2)
print(random_1 == rand0m_2)

tensor([[0.8718, 0.6135, 0.5741],
        [0.9472, 0.0660, 0.1360],
        [0.5689, 0.7477, 0.4681]])
tensor([[0.7920, 0.7413, 0.0611],
        [0.2316, 0.6231, 0.2513],
        [0.5449, 0.4632, 0.2488]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [81]:
#REPRODUCIBLE
Random_seed = 15
torch.manual_seed(Random_seed)
random_3 = torch.rand(3,3)
torch.manual_seed(Random_seed)
random_4 = torch.rand(3,3)
print(random_3)
print(random_4)
print(random_3 == random_4)

tensor([[0.2973, 0.2766, 0.7974],
        [0.3869, 0.9170, 0.4125],
        [0.5538, 0.5646, 0.5026]])
tensor([[0.2973, 0.2766, 0.7974],
        [0.3869, 0.9170, 0.4125],
        [0.5538, 0.5646, 0.5026]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [82]:
random_3

tensor([[0.2973, 0.2766, 0.7974],
        [0.3869, 0.9170, 0.4125],
        [0.5538, 0.5646, 0.5026]])

In [83]:
#Set up device agnostic code
device = "cuda" if torch.cuda.is_availabe() else "cpu"
device

AttributeError: module 'torch.cuda' has no attribute 'is_availabe'

In [85]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu
