<a href="https://colab.research.google.com/github/Suhuyini15/PYTORCH_P/blob/main/00_PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


CREATING TENSORS


In [2]:
#SCALAR

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#gET TENSOR AS PYTHON int
scalar.item()

7

In [5]:
#VECTOR
vector = torch.tensor([2,6])
vector

tensor([2, 6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [2,6]])

MATRIX

tensor([[7, 8],
        [2, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([2, 6])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],[5,9,1],
                       [6,4,7]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 9, 1],
        [6, 4, 7]])

In [16]:
MATRIX2 = torch.tensor([[[7,0,4],
            [5,9,1],
            [6,3,5]]])

In [17]:
MATRIX2.ndim

3

RANDOM TENSORS

Neural network pattern

```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
```



In [18]:
#Random Tensors
random_tensor = torch.rand(5, 4,6)
random_tensor

tensor([[[0.0455, 0.9979, 0.2375, 0.9244, 0.0577, 0.1415],
         [0.8151, 0.3250, 0.7298, 0.3444, 0.8286, 0.0691],
         [0.2664, 0.6627, 0.0579, 0.0642, 0.1174, 0.2129],
         [0.7475, 0.3017, 0.2772, 0.1527, 0.9297, 0.1488]],

        [[0.9374, 0.8590, 0.3006, 0.0733, 0.7622, 0.2323],
         [0.4639, 0.8776, 0.6628, 0.7611, 0.0718, 0.9110],
         [0.3674, 0.3092, 0.7689, 0.6370, 0.6855, 0.0546],
         [0.1992, 0.4472, 0.1885, 0.5791, 0.1402, 0.5790]],

        [[0.8243, 0.7731, 0.6195, 0.5906, 0.7688, 0.4146],
         [0.3948, 0.1558, 0.2631, 0.3501, 0.9530, 0.1300],
         [0.9232, 0.9489, 0.5919, 0.2924, 0.3555, 0.8285],
         [0.3175, 0.0828, 0.1849, 0.3863, 0.4466, 0.3952]],

        [[0.5557, 0.2541, 0.8837, 0.7934, 0.4538, 0.4512],
         [0.9853, 0.2185, 0.5958, 0.2082, 0.4117, 0.5485],
         [0.3772, 0.3523, 0.2429, 0.9894, 0.0312, 0.9203],
         [0.8775, 0.6105, 0.4575, 0.7837, 0.5284, 0.3806]],

        [[0.8643, 0.4526, 0.3484, 0.5687, 0.6458

In [19]:
random_tensor.ndim

3

In [20]:
#Tensor with shape similar to an image
random_image_tensor = torch.rand(size =(224,224,3))# height, widht ,color channel
random_image_tensor.shape,random_image_tensor.ndim





(torch.Size([224, 224, 3]), 3)

In [21]:
CAT_TENSOR = torch.rand(2,7,2,2)
CAT_TENSOR

tensor([[[[0.8905, 0.5001],
          [0.2083, 0.0487]],

         [[0.0149, 0.7546],
          [0.9931, 0.9512]],

         [[0.1497, 0.2013],
          [0.9521, 0.2596]],

         [[0.8995, 0.2952],
          [0.1950, 0.8142]],

         [[0.6109, 0.0235],
          [0.7882, 0.0964]],

         [[0.1508, 0.1238],
          [0.6917, 0.6114]],

         [[0.1354, 0.3671],
          [0.5725, 0.9424]]],


        [[[0.7100, 0.0592],
          [0.8682, 0.6066]],

         [[0.8139, 0.0285],
          [0.2203, 0.6243]],

         [[0.8771, 0.7466],
          [0.7970, 0.5443]],

         [[0.6669, 0.1158],
          [0.3584, 0.3432]],

         [[0.6131, 0.7046],
          [0.5364, 0.6104]],

         [[0.1984, 0.4559],
          [0.4598, 0.6620]],

         [[0.9874, 0.5037],
          [0.8260, 0.4389]]]])

In [22]:
CAT_TENSOR.ndim, CAT_TENSOR.shape

(4, torch.Size([2, 7, 2, 2]))

In [23]:
PAINT_IMAGE = torch.rand(size=(155,155,1))

In [24]:
PAINT_IMAGE.ndim, PAINT_IMAGE.shape

(3, torch.Size([155, 155, 1]))

**ZEROS AND ONES**

In [25]:
Zeros = torch.zeros(5,4,6)
Zeros

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [26]:
Zeros*random_tensor

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [27]:
Ones = torch.ones(size=(5,9))
Ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
numbers = torch.arange(1000,1000000,10000)
numbers

tensor([  1000,  11000,  21000,  31000,  41000,  51000,  61000,  71000,  81000,
         91000, 101000, 111000, 121000, 131000, 141000, 151000, 161000, 171000,
        181000, 191000, 201000, 211000, 221000, 231000, 241000, 251000, 261000,
        271000, 281000, 291000, 301000, 311000, 321000, 331000, 341000, 351000,
        361000, 371000, 381000, 391000, 401000, 411000, 421000, 431000, 441000,
        451000, 461000, 471000, 481000, 491000, 501000, 511000, 521000, 531000,
        541000, 551000, 561000, 571000, 581000, 591000, 601000, 611000, 621000,
        631000, 641000, 651000, 661000, 671000, 681000, 691000, 701000, 711000,
        721000, 731000, 741000, 751000, 761000, 771000, 781000, 791000, 801000,
        811000, 821000, 831000, 841000, 851000, 861000, 871000, 881000, 891000,
        901000, 911000, 921000, 931000, 941000, 951000, 961000, 971000, 981000,
        991000])

In [29]:
#Creating tensosr like (A tensor with the shpae like another or previous tensor)
numbers_zeros = torch.zeros_like(input=numbers)
numbers_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [30]:
numbers_ones = torch.ones_like(input=numbers)
numbers_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

**TENSOR DATATYPES**

In [32]:
FLOAT_32_TENSOR = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,# tensor datatype
                               device='cpu', # devive of tensor
                               requires_grad=False) # track gradient or not
FLOAT_32_TENSOR

tensor([3., 6., 9.])

In [33]:
FLOAT_32_TENSOR.dtype

torch.float32

In [38]:
#CHANGE TENSOR DYTPE
FLOAT_16_TENSOR = FLOAT_32_TENSOR.type(torch.float16)
FLOAT_16_TENSOR

tensor([3., 6., 9.], dtype=torch.float16)

In [68]:
from typing import Tuple
new_tensor = torch.tensor([[1,7],[6,8]],
                          dtype=None,
                          device='cpu',
                          requires_grad=False)
new_tensor.dtype

torch.int64

In [86]:
sample_tensor = torch.empty((5,8), dtype=torch.int8, requires_grad=False)
sample_tensor

tensor([[   0,  -95,  -51,   32,  -12,  121,    0,    0],
        [ 112, -112,  -51,   32,  -12,  121,    0,    0],
        [ 112,  -97,  -51,   32,  -12,  121,    0,    0],
        [  16,  -96,  -51,   32,  -12,  121,    0,    0],
        [ -32, -119,  -51,   32,  -12,  121,    0,    0]], dtype=torch.int8)

In [89]:
sample_tensor = sample_tensor.type(torch.cdouble)
sample_tensor

tensor([[   0.+0.j,  -95.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [ 112.+0.j, -112.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [ 112.+0.j,  -97.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [  16.+0.j,  -96.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [ -32.+0.j, -119.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j]],
       dtype=torch.complex128)

*`torch.empty` for creating placeholder tensors.
`torch.tensor` for creating actual tensor with real data *

In [88]:
FLOAT_16_TENSOR*FLOAT_32_TENSOR

tensor([ 9., 36., 81.])

In [90]:
sample2 = torch.ones_like(input=sample_tensor)
sample2

tensor([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]],
       dtype=torch.complex128)

In [98]:
sample2 = sample2.type(torch.int)
sample2

tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)

In [99]:
sample_tensor*sample2

tensor([[   0.+0.j,  -95.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [ 112.+0.j, -112.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [ 112.+0.j,  -97.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [  16.+0.j,  -96.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j],
        [ -32.+0.j, -119.+0.j,  -51.+0.j,   32.+0.j,  -12.+0.j,  121.+0.j,    0.+0.j,    0.+0.j]],
       dtype=torch.complex128)

 **TOP ERRORS **
1. TENSOR NOT RIGHT DATATYPE
2. TENSOR NOT RIGHT SHAPE
3. TENSOR NOT ON THE RIGHT DEVICE

In [102]:
#GETTING INFO FROM TENSORS
a_tensor = torch.rand(5,3)
a_tensor

tensor([[0.0474, 0.1844, 0.9400],
        [0.0094, 0.7140, 0.0400],
        [0.4217, 0.5422, 0.3087],
        [0.6851, 0.6552, 0.9737],
        [0.2010, 0.5845, 0.5442]])

In [107]:
print(f"Datatype of tensor: {a_tensor.dtype}")
print(f"Shape of tensor: {a_tensor.shape}")
print(f"Device of tensor: {a_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([5, 3])
Device of tensor: cpu


In [ ]:
# CHANGING DEVICE OF TENSOR
a_tensor = a_tensor.to(device='cpu')
print(f"Device of tensor: {a_tensor.device}")

In [114]:
## ADDITION OF TENSORS
mani_t = torch.tensor([[1,6],[2,8]])
mani_t = mani_t + 3

In [115]:
#MULTIPLY TENSORS
mani_t * 3

tensor([[12, 27],
        [15, 33]])

In [116]:
mani_t

tensor([[ 4,  9],
        [ 5, 11]])

In [118]:
#SUBTRACT
mani_t - 15

tensor([[-11,  -6],
        [-10,  -4]])

In [119]:
#MATRIX FUNCTIONS
torch.mul(mani_t, 1)

tensor([[ 4,  9],
        [ 5, 11]])

In [122]:
## MATRIX MULTIPLICATION
#ELEMENT WISE
print(mani_t ,"*" , mani_t)
print(f"Equals: {mani_t * mani_t}")

tensor([[ 4,  9],
        [ 5, 11]]) * tensor([[ 4,  9],
        [ 5, 11]])
Equals: tensor([[ 16,  81],
        [ 25, 121]])


In [124]:
#MATRIX WISE
torch.matmul(mani_t, mani_t)

tensor([[ 61, 135],
        [ 75, 166]])